// Generated by Wrangler by running `wrangler types`

interface Env {
	LOKEEL_STOCK_SCREENER_KV: KVNamespace;
	API_TOKEN: string;
	ALLOWED_ORIGIN: string;
	STOCKS_BASE_URL: string;
	AZURE_AD_TOKEN_URL: string;
	AZURE_AD_LOGOUT_URL: string;
	AZURE_SPA_CLIENT_ID: string;
	AZURE_API_CLIENT_ID: string;
	AZURE_SPA_REDIRECT_URI: string;
	DEV: string;
	PUBLIC_KEY_TENANT: string;
	PUBLIC_KEY_POLICY_ID: string;
	STRIPE_API_KEY: string;
	RSA_PRIVATE_KEY: string;
	BASE_PLAN: string;
}
